# Generated by Django 6.0.2 on 2026-02-04 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisaApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(blank=True, help_text='Leave empty for random selection', max_length=10)),
                ('visa', models.CharField(choices=[('1', 'Tourisme Simple'), ('2', 'Tourisme Multiple'), ('3', 'Affaires Simple'), ('4', 'Affaires Multiple'), ('5', 'Traitement Simple'), ('6', 'Traitement Multiple'), ('32', 'Étudiant Simple'), ('34', 'Accompagnement Simple'), ('35', 'Accompagnement Multiple'), ('38', 'Permis de Travail Simple'), ('39', 'Permis de Travail Multiple'), ('40', 'Transit Double'), ('77', 'Transit Simple')], default='1', max_length=2)),
                ('nationality', models.CharField(choices=[('31', 'Algérie'), ('1', "États-Unis d'Amérique"), ('77', 'Royaume-Uni'), ('35', 'Chine'), ('71', 'Inde'), ('84', 'Italie'), ('91', 'Canada'), ('9', 'Australie'), ('3', 'Allemagne'), ('55', 'France'), ('80', 'Espagne'), ('191', 'Turquie')], default='31', max_length=3)),
                ('contact_address', models.TextField()),
                ('contact_city', models.CharField(max_length=100)),
                ('contact_postcode', models.CharField(max_length=10)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('auto_click_next', models.BooleanField(default=False)),
                ('auto_click_delay', models.IntegerField(default=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference_id', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birthday', models.DateField()),
                ('birth_place', models.CharField(max_length=100)),
                ('marital_status', models.CharField(choices=[('0', 'Single'), ('1', 'Married')], max_length=1)),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('occupation', models.CharField(choices=[('Agriculture', 'Agriculture'), ('Armed/Security Force', 'Armed/Security Force'), ('Artist/Performer', 'Artist/Performer'), ('Business', 'Business'), ('Caregiver/Babysitter', 'Caregiver/Babysitter'), ('Construction', 'Construction'), ('Culinary/Cookery', 'Culinary/Cookery'), ('Driver/Lorry', 'Driver/Lorry'), ('Education/Training', 'Education/Training'), ('Engineer', 'Engineer'), ('Finance/Banking', 'Finance/Banking'), ('Government', 'Government'), ('Health/Medical', 'Health/Medical'), ('Information Technologies', 'Information Technologies'), ('Legal Professional', 'Legal Professional'), ('Other', 'Other'), ('Press/Media', 'Press/Media'), ('Professional Sportsperson', 'Professional Sportsperson'), ('Religious Functionary', 'Religious Functionary'), ('Researcher/Scientist', 'Researcher/Scientist'), ('Retired', 'Retired'), ('Seafarer', 'Seafarer'), ('Self-Employed', 'Self-Employed'), ('Service Sector', 'Service Sector'), ('Student/Trainee', 'Student/Trainee'), ('Tourism', 'Tourism'), ('Unemployed', 'Unemployed')], max_length=50)),
                ('passport_issued_by', models.CharField(max_length=100)),
                ('passport_issue_date', models.DateField()),
                ('passport_expiry', models.DateField()),
                ('travel_document', models.CharField(choices=[('3', 'Passeport Diplomatique'), ('2', "Carte d'Identité"), ('10', 'Passeport Ordinaire'), ('9', 'Autres'), ('11', 'Document de Voyage pour Réfugiés')], default='10', max_length=2)),
                ('order', models.IntegerField(default=0)),
                ('visa_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='visa_form.visaapplication')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
